export default function getEditorColors(scheme, term) {
  return {
    "editor.background": scheme.background,
    "editor.foreground": scheme.onBackground,
    "editorLineNumber.foreground": scheme.onSurfaceVariant,
    "editorLineNumber.activeForeground": `${scheme.primary}99`,
    "editorLineNumber.dimmedForeground": scheme.outlineVariant,
    "editorCursor.background": scheme.surfaceContainer,
    "editorCursor.foreground": scheme.primary,
    "editorMultiCursor.primary.foreground": scheme.primary,
    "editorMultiCursor.primary.background": `${scheme.primaryContainer}4D`,
    "editorMultiCursor.secondary.foreground": scheme.secondary,
    "editorMultiCursor.secondary.background": `${scheme.secondaryContainer}4D`,
    "editor.placeholder.foreground": scheme.onSurfaceVariant,
    "editor.compositionBorder": `${scheme.background}00`,

    "editor.selectionBackground": `${scheme.primary}1A`,
    "editor.selectionForeground": scheme.onPrimary,
    "editor.inactiveSelectionBackground": `${scheme.primary}0A`,
    "editor.selectionHighlightBackground": `${scheme.secondary}1A`,
    "editor.selectionHighlightBorder": `${scheme.background}00`,

    "editor.wordHighlightBackground": `${scheme.secondary}33`,
    "editor.wordHighlightBorder": `${scheme.background}00`,
    "editor.wordHighlightStrongBackground": `${scheme.secondary}66`,
    "editor.wordHighlightStrongBorder": `${scheme.background}00`,
    "editor.wordHighlightTextBackground": `${scheme.tertiary}0A`,
    "editor.wordHighlightTextBorder": `${scheme.background}00`,

    "editor.findMatchBackground": `${scheme.tertiary}66`,
    "editor.findMatchForeground": scheme.onSurface,
    "editor.findMatchHighlightForeground": `${scheme.onSurface}80`,
    "editor.findMatchHighlightBackground": `${scheme.tertiary}0A`,
    "editor.findRangeHighlightBackground": `${scheme.surfaceVariant}40`,
    "editor.findMatchBorder": `${scheme.background}00`,
    "editor.findMatchHighlightBorder": `${scheme.background}00`,
    "editor.findRangeHighlightBorder": `${scheme.background}00`,

    "search.resultsInfoForeground": scheme.onSurfaceVariant,

    "searchEditor.findMatchBackground": `${scheme.primary}0A`,
    "searchEditor.findMatchBorder": `${scheme.background}00`,
    "searchEditor.textInputBorder": `${scheme.background}00`,

    "editor.hoverHighlightBackground": `${scheme.secondary}1A`,

    "editor.lineHighlightBackground": `${scheme.surfaceContainer}1A`,
    "editor.lineHighlightBorder": `${scheme.background}00`,

    "editorUnicodeHighlight.border": `${scheme.background}00`,
    "editorUnicodeHighlight.background": scheme.surfaceContainer,

    "editorLink.activeForeground": scheme.primary,

    "editor.rangeHighlightBackground": `${scheme.surfaceContainer}4D`,
    "editor.rangeHighlightBorder": `${scheme.background}00`,

    "editor.symbolHighlightBackground": `${scheme.secondaryContainer}33`,
    "editor.symbolHighlightBorder": `${scheme.background}00`,

    "editorWhitespace.foreground": `${scheme.onSurfaceVariant}66`,

    "editorIndentGuide.background1": `${term.normal.blue}26`,
    "editorIndentGuide.background2": `${term.normal.cyan}26`,
    "editorIndentGuide.background3": `${term.normal.green}26`,
    "editorIndentGuide.background4": `${term.normal.yellow}26`,
    "editorIndentGuide.background5": `${term.normal.magenta}26`,
    "editorIndentGuide.background6": `${term.bright.blue}26`,
    "editorIndentGuide.activeBackground1": term.normal.blue,
    "editorIndentGuide.activeBackground2": term.normal.cyan,
    "editorIndentGuide.activeBackground3": term.normal.green,
    "editorIndentGuide.activeBackground4": term.normal.yellow,
    "editorIndentGuide.activeBackground5": term.normal.magenta,
    "editorIndentGuide.activeBackground6": term.bright.blue,

    "editorInlayHint.background": scheme.surfaceContainer,
    "editorInlayHint.foreground": scheme.onSurfaceVariant,
    "editorInlayHint.typeForeground": scheme.onTertiaryContainer,
    "editorInlayHint.typeBackground": scheme.tertiaryContainer,
    "editorInlayHint.parameterForeground": scheme.onSecondaryContainer,
    "editorInlayHint.parameterBackground": scheme.secondaryContainer,

    "editorRuler.foreground": `${scheme.outlineVariant}66`,

    "editor.linkedEditingBackground": scheme.surfaceContainer,
    "editorCodeLens.foreground": scheme.onSurfaceVariant,
    "editorLightBulb.foreground": scheme.tertiary,
    "editorLightBulbAutoFix.foreground": scheme.secondary,
    "editorLightBulbAi.foreground": scheme.primary,
    "editorBracketMatch.background": `${term.normal.blue}1A`,
    "editorBracketMatch.border": `${scheme.background}00`,
    "editorBracketHighlight.foreground1": term.normal.blue,
    "editorBracketHighlight.foreground2": term.normal.cyan,
    "editorBracketHighlight.foreground3": term.normal.green,
    "editorBracketHighlight.foreground4": term.normal.yellow,
    "editorBracketHighlight.foreground5": term.normal.magenta,
    "editorBracketHighlight.foreground6": term.bright.blue,
    "editorBracketHighlight.unexpectedBracket.foreground": scheme.error,
    "editorBracketPairGuide.activeBackground1": `${term.normal.blue}33`,
    "editorBracketPairGuide.activeBackground2": `${term.normal.cyan}33`,
    "editorBracketPairGuide.activeBackground3": `${term.normal.green}33`,
    "editorBracketPairGuide.activeBackground4": `${term.normal.yellow}33`,
    "editorBracketPairGuide.activeBackground5": `${term.normal.magenta}33`,
    "editorBracketPairGuide.activeBackground6": `${term.bright.blue}33`,
    "editorBracketPairGuide.background1": `${term.normal.blue}1A`,
    "editorBracketPairGuide.background2": `${term.normal.cyan}1A`,
    "editorBracketPairGuide.background3": `${term.normal.green}1A`,
    "editorBracketPairGuide.background4": `${term.normal.yellow}1A`,
    "editorBracketPairGuide.background5": `${term.normal.magenta}1A`,
    "editorBracketPairGuide.background6": `${term.bright.blue}1A`,
    "editor.foldBackground": `${scheme.tertiaryContainer}26`,
    "editor.foldPlaceholderForeground": scheme.outlineVariant,
    "editorOverviewRuler.background": scheme.surfaceContainer,
    "editorOverviewRuler.border": `${scheme.background}00`,
    "editorOverviewRuler.findMatchForeground": `${term.normal.yellow}80`,
    "editorOverviewRuler.rangeHighlightForeground": `${scheme.surfaceVariant}40`,
    "editorOverviewRuler.selectionHighlightForeground": `${term.normal.blue}80`,
    "editorOverviewRuler.wordHighlightForeground": `${scheme.outline}80`,
    "editorOverviewRuler.wordHighlightStrongForeground": `${scheme.outlineVariant}40`,
    "editorOverviewRuler.wordHighlightTextForeground": `${scheme.onSurfaceVariant}80`,
    "editorOverviewRuler.modifiedForeground": term.normal.blue,
    "editorOverviewRuler.addedForeground": term.normal.green,
    "editorOverviewRuler.deletedForeground": term.normal.red,
    "editorOverviewRuler.errorForeground": scheme.error,
    "editorOverviewRuler.warningForeground": term.normal.yellow,
    "editorOverviewRuler.infoForeground": term.normal.blue,
    "editorOverviewRuler.bracketMatchForeground": term.normal.blue,
    "editorOverviewRuler.inlineChatInserted": term.normal.green,
    "editorOverviewRuler.inlineChatRemoved": term.normal.red,
    "editorError.foreground": scheme.error,
    "editorError.border": `${scheme.background}00`,
    "editorError.background": `${scheme.errorContainer}33`,
    "editorWarning.foreground": term.normal.yellow,
    "editorWarning.border": `${scheme.background}00`,
    "editorWarning.background": `${term.normal.yellow}33`,
    "editorInfo.foreground": term.normal.blue,
    "editorInfo.background": `${term.normal.blue}33`,
    "editorInfo.border": `${scheme.background}00`,
    "editorHint.foreground": term.normal.cyan,
    "editorHint.border": `${scheme.background}00`,
    "problemsErrorIcon.foreground": scheme.error,
    "problemsWarningIcon.foreground": term.normal.yellow,
    "problemsInfoIcon.foreground": term.normal.blue,
    "editorUnnecessaryCode.border": `${scheme.background}00`,
    "editorUnnecessaryCode.opacity": scheme.onSurfaceVariant,
    "editorGutter.background": scheme.surfaceContainer,
    "editorGutter.modifiedBackground": term.normal.blue,
    "editorGutter.addedBackground": term.normal.green,
    "editorGutter.deletedBackground": term.normal.red,
    "editorGutter.commentRangeForeground": term.normal.blue,
    "editorGutter.commentGlyphForeground": scheme.onSurfaceVariant,
    "editorGutter.commentUnresolvedGlyphForeground": term.normal.blue,
    "editorGutter.foldingControlForeground": scheme.onSurface,
    "editorCommentsWidget.resolvedBorder": `${scheme.background}00`,
    "editorCommentsWidget.unresolvedBorder": `${scheme.background}00`,
    "editorCommentsWidget.rangeBackground": scheme.surfaceContainer,
    "editorCommentsWidget.rangeActiveBackground": scheme.surfaceContainerHigh,
    "editorCommentsWidget.replyInputBackground": scheme.surfaceContainerLowest,

    "inlineEdit.gutterIndicator.primaryBorder": `${scheme.background}00`,
    "inlineEdit.gutterIndicator.primaryForeground": scheme.onPrimary,
    "inlineEdit.gutterIndicator.primaryBackground": term.normal.blue,
    "inlineEdit.gutterIndicator.secondaryBorder": `${scheme.background}00`,
    "inlineEdit.gutterIndicator.secondaryForeground": scheme.onSecondary,
    "inlineEdit.gutterIndicator.secondaryBackground": term.normal.cyan,
    "inlineEdit.gutterIndicator.successfulBorder": `${scheme.background}00`,
    "inlineEdit.gutterIndicator.successfulForeground": scheme.onTertiary,
    "inlineEdit.gutterIndicator.successfulBackground": term.normal.green,
    "inlineEdit.gutterIndicator.background": scheme.surfaceContainer,
    "inlineEdit.originalBackground": `${term.normal.red}26`,
    "inlineEdit.modifiedBackground": `${term.normal.green}26`,
    "inlineEdit.originalChangedLineBackground": `${term.normal.red}1A`,
    "inlineEdit.originalChangedTextBackground": `${term.normal.red}33`,
    "inlineEdit.modifiedChangedLineBackground": `${term.normal.green}1A`,
    "inlineEdit.modifiedChangedTextBackground": `${term.normal.green}33`,
    "inlineEdit.originalBorder": `${scheme.background}00`,
    "inlineEdit.modifiedBorder": `${scheme.background}00`,
    "inlineEdit.tabWillAcceptModifiedBorder": `${scheme.background}00`,
    "inlineEdit.tabWillAcceptOriginalBorder": `${scheme.background}00`,
  };
}
